<h1>Apple a Day :)</h1>
<p>Sometimes you want a cupcake. Sometimes you want a piece of pie. Sometimes you want both! Our Apple Spice Cupcake comes with an apple filling topped with a buttercream frosting wrapped in an adorable fondant design.</p>
<img src="http://farm6.staticflickr.com/5479/9527671212_e7812fc351_c.jpg" width="800" height="534" alt="apple-spice-cupcake-with-jelly-filling-and-buttercream-frosting" />
<p>The cupcakes are baked to perfection. A glazed top compliments the fresh cake texture. The spice cake comes to life with every bite. A hit of chocolate makes you crave every bite.</p>
<img src="http://farm6.staticflickr.com/5469/9524887061_42d90929df_n.jpg" width="320" height="213" alt="apple-spice-cupcake" />
<p>The second most important part of a cupcake is the frosting. A homemade buttercream frosting is whipped gently into a creamy and flavorful combination.</p>
<img src="http://farm6.staticflickr.com/5471/9527670556_8006ccfee3_n.jpg" width="320" height="213" alt="buttercream" />
<img src="http://farm8.staticflickr.com/7378/9527670228_bb3dab36cf_n.jpg" width="320" height="213" alt="buttercream-bag" />
<p>The next ingredient is a secret recipe. A local Apple Preserve is used for the cupcake filling. You don't need a lot, this jelly packs an amazing punch. It's a perfect compliment to the spice cake.</p>
<img src="http://farm6.staticflickr.com/5511/9524887365_5fdcc68fed_n.jpg" width="320" height="213" alt="apple-preserves" />
<img src="http://farm3.staticflickr.com/2883/9527670146_9f478edcf0_n.jpg" width="320" height="213" alt="frosting-and-filling-bag" />
<p>The real magic happens when all of these flavors are put together. Our first step, core the app.. I mean, cupcake.</p>
<img src="http://farm3.staticflickr.com/2812/9524886453_f3a43ed4e3_c.jpg" width="800" height="534" alt="apple-spice-cupcake-before-filling" />
<p>Commence the filling and icing ceremony. We go a little crazy here because we can. Fill to the max and don't hold back on the icing!</p>
<img src="http://farm4.staticflickr.com/3791/9524886769_18837ac26f_n.jpg" width="320" height="213" alt="apple-spice-cupcake-after-filling" />
<img src="http://farm6.staticflickr.com/5346/9524889763_d1dfef3313_n.jpg" width="320" height="213" alt="spice-cupcake-with-apple-filling">
<img src="http://farm8.staticflickr.com/7285/9524891447_b1556b3ee9_n.jpg" width="320" height="213" alt="icing-an-apple-spice-cupcake" />
<img src="http://farm4.staticflickr.com/3671/9527676242_8c3733da3c_n.jpg" width="320" height="213" alt="icing-an-apple-spice-cupcake2" />
<img src="http://farm4.staticflickr.com/3797/9527674508_9acf76392f_n.jpg" width="320" height="213" alt="spice-cupcake-with-buttercream" />
<p>At this point we could be finished. This is an excellent tasting cupcake at this point. Believe me, it is! But why stop here? Take one last close look at that light and fluffy buttercream frosting :)</p>
<img src="http://farm8.staticflickr.com/7440/9524889173_2c96840773_c.jpg" width="800" height="534" alt="spice-cupcake-with-buttercream2" />
<p>Time to ripen this apple ready for pickins! We cover the cupcake in a beautiful red fondant. We make a depression at the top and stub in our stem.</p>
<img src="http://farm4.staticflickr.com/3743/9527675144_654bcb90c2_n.jpg" width="320" height="213" alt="red-fondant" />
<img src="http://farm4.staticflickr.com/3688/9527673124_d294c930bf_n.jpg" width="320" height="213" alt="apple-cupcake-top" />
<img src="http://farm6.staticflickr.com/5456/9527672752_1ff0664509_n.jpg" width="320" height="213" alt="apple-cupcake-top2" />
<img src="http://farm6.staticflickr.com/5512/9527673388_9974b8dae9_n.jpg" width="320" height="213" alt="apple-cupcake-stem" />
<p>Time for the finishing touch. Every apple needs a leaf! We stamp out some greenery carve out the design.</p>
<img src="http://farm8.staticflickr.com/7293/9527676878_39b639463d_n.jpg" width="320" height="213" alt="green-fondant" />
<img src="http://farm6.staticflickr.com/5453/9527675886_6f209dcc58_n.jpg" width="320" height="213" alt="leaf-cutout-green-fondant" />
<img src="http://farm3.staticflickr.com/2839/9527675526_15d847f7d3_n.jpg" width="320" height="213" alt="leaf-pattern" />
<img src="http://farm3.staticflickr.com/2869/9527673888_b700761a01_n.jpg" width="320" height="213" alt="three-leaves" />
<img src="http://farm3.staticflickr.com/2867/9524885789_0945812bb4_n.jpg" width="320" height="213" alt="bunch-of-leaves" />
<p>Put it all together and you get an Apple Cupcake!</p>
<img src="http://farm8.staticflickr.com/7411/9524888471_f7f2d15b09_c.jpg" width="800" height="534" alt="apple-cupcake" />
<p><small>Our photos are hosted on <a href="http://www.flickr.com/photos/100364653@N02/sets/">Flickr</a></small></p>
<p>For more information on ordering this or our other Cakes and Cupcakes please <a href="<?php echo $this->url('contact'); ?>">contact us</a> :)</p>