<footer class="site-footer container_12">
    <section class="grid_4">
        <header>
            <h2>About</h2>
        </header>
        <p>Rebecca Yawman is the founder and owner of Sweet Cakes. She is a wife, a mother, a sister, a friend and last but certainly not least, a Baker! <a href="/contact">Contact Rebecca &raquo;</a></p>
    </section>
    <section class="grid_4">
        <header>
            <h2>Articles</h2>
        </header>
        <ul>
            <li><a href="/">Apple Spice Cupcake with Buttercream Frosting</a></li>
            <li><a href="/">Chocolate Fudge Cake with Cream Filling</a></li>
            <li><a href="/">See all articles</a></li>
        </ul>
    </section>
    <section class="grid_4">
        <header>
            <h2>Showcase</h2>
        </header>
        <img src="/img/apple-thumb.png" alt="Apple Spice Cupcake with Buttercream Frosting" style="background-color: #fff; border:2px solid #000; padding:2px; margin:2px; float:right;" />
        <p>Apple Spice Cupcake with an Apple Jelly Filling and a Buttercream Frosting. <br/> <a href="/">Check it out &raquo;</a></p>
    </section>
</footer>
<div class="container_12">
    <p class="grid_12">Copyright &copy; <?php echo date('Y'); ?> Sweet Cakes. All Rights Reserved</p>
</div>