<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <?php echo $this->headTitle('Sweet Cakes | Virginia Beach Cake Decorator and Designer') ?>

        <?php $this->headLink()->appendStylesheet('/css/app.css'); ?>
        <?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js') ?>
        <?php $this->headScript()->appendFile('/js/app.js') ?>

        <?php echo $this->headLink(); ?>
    </head>
    <body>
        <?php echo $this->navigation()->menu('site_navigation'); ?>
        <?php echo $this->navigation()->breadcrumbs('site_navigation')->setLinkLast(true)->setMinDepth(0)->setMaxDepth(3)->setSeparator('&raquo;'); ?>
        <?php echo $this->content; ?>
        <div id="disqus_thread"></div>
        <script type="text/javascript">
            /* * * CONFIGURATION VARIABLES: EDIT BEFORE PASTING INTO YOUR WEBPAGE * * */
            var disqus_shortname = 'vbsweetcakes'; // required: replace example with your forum shortname

            /* * * DON'T EDIT BELOW THIS LINE * * */
            (function() {
                var dsq = document.createElement('script'); dsq.type = 'text/javascript'; dsq.async = true;
                dsq.src = '//' + disqus_shortname + '.disqus.com/embed.js';
                (document.getElementsByTagName('head')[0] || document.getElementsByTagName('body')[0]).appendChild(dsq);
            })();
        </script>
        <noscript>Please enable JavaScript to view the <a href="http://disqus.com/?ref_noscript">comments powered by Disqus.</a></noscript>
        <a href="http://disqus.com" class="dsq-brlink">comments powered by <span class="logo-disqus">Disqus</span></a>
        <?php echo $this->headScript(); ?>
    </body>
</html>