<?php echo $this->doctype(); ?>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <?php echo $this->headTitle('Sweet Cakes | Virginia Beach Cake Decorator and Designer') ?>

        <?php $this->headLink()->appendStylesheet('//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap.min.css'); ?>
        <?php $this->headLink()->appendStylesheet('/css/app.css'); ?>
        <?php $this->headScript()->appendFile('http://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js') ?>
        <?php $this->headScript()->appendFile('//netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js') ?>
        <?php $this->headScript()->appendFile('/js/app.js') ?>

        <?php echo $this->headLink(); ?>
        <?php echo $this->headScript(); ?>
        <link href='http://fonts.googleapis.com/css?family=Bigelow+Rules' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Cherry+Swash' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Mystery+Quest' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=Shadows+Into+Light+Two' rel='stylesheet' type='text/css'>
        <link href='http://fonts.googleapis.com/css?family=The+Girl+Next+Door' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <div class="logo-wrapper">
            <div class="container">
                <a href="/"><img src="/img/logo-text.png" class="img-responsive" /></a>
            </div>
        </div>
        <div class="navbar-wrapper">
            <div class="container">
                <div class="navbar navbar-default">
                    <div class="navbar-header">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                    </div>
                    <div class="navbar-collapse collapse">
                        <ul class="nav navbar-nav">
                            <li class="active first"><a href="/">HOME</a></li>
                            <li class="divider-vertical hidden-xs">|</li>
                            <li><a href="/#showcase">SHOWCASE</a></li>
                            <li class="divider-vertical hidden-xs">|</li>
                            <li><a href="/#custom-cakes">CUSTOM CAKES</a></li>
                            <li class="divider-vertical hidden-xs">|</li>
                            <li><a href="/#about">ABOUT</a></li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <?php echo $this->content; ?>
        <div class="footer-wrapper">
            <div class="container">
                <p><?php echo date('Y'); ?> Copyright. All Rights Reserved. Virginia Beach Sweet Cakes.</p>
            </div>
        </div>
    </body>
</html>
