Contact
<?php
$form = $this->form;
$form->prepare();
$form->setAttribute('action', $this->url('contact'));
$form->setAttribute('method', 'post');
$formLabel = $this->plugin('formLabel');
echo $this->form()->openTag($form);
?>
<div class="form_element">
    <?php
    $name = $form->get('name');
    echo $formLabel->openTag() . $name->getOption('label');
    echo $this->formInput($name);
    echo $this->formElementErrors($name);
    echo $formLabel->closeTag();
    ?>
</div>

<div class="form_element">
    <?php
    $email = $form->get('email');
    echo $formLabel->openTag() . $email->getOption('label');
    echo $this->formInput($email);
    echo $this->formElementErrors($email);
    echo $formLabel->closeTag();
    ?>
</div>

<div class="form_element">
    <?php
    $phone = $form->get('phone');
    echo $formLabel->openTag() . $phone->getOption('label');
    echo $this->formInput($phone);
    echo $this->formElementErrors($phone);
    echo $formLabel->closeTag();
    ?>
</div>

<div class="form_element">
    <?php
    $comments = $form->get('comments');
    echo $formLabel->openTag() . $comments->getOption('label');
    echo $this->formTextarea($comments);
    echo $this->formElementErrors($comments);
    echo $formLabel->closeTag();
    ?>
</div>

<?php echo $this->formElement($form->get('security')) ?>
<?php echo $this->formElement($form->get('send')) ?>

<?php echo $this->form()->closeTag() ?>