<?php $escaper = new Zend\Escaper\Escaper('utf-8'); ?>
<div class="jumbotron">
    <div class="container">
        <div class="row">
            <div class="col-xs-6 col-sm-6 col-md-6">
                <div id="homepage-carousel" class="carousel slide">
                    <div class="carousel-inner">
                        <div class="item active">
                            <img src="/img/photos/baby-announcement-cake.jpg" alt="Baby Announcement Cake" class="frame img-responsive" />
                            <div class="carousel-caption hidden-xs hidden-sm">
                                <h3>Baby Announcement Cake</h3>
                            </div>
                        </div>
                        <div class="item">
                            <img src="/img/photos/purple-rose-bud-anniversary-cake.jpg" alt="Purple Rose Bud Anniversary Cake for 2" class="frame img-responsive" />
                            <div class="carousel-caption hidden-xs hidden-sm">
                                <h3>Purple Rose Bud Cake</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-xs-6 col-sm-6 col-md-6">
                <img src="/img/beautiful-delicious-cakes.png" alt="Beautiful and Delicious Cakes" class="img-responsive" style="margin-top:20px;" />
            </div>

        </div>

    </div>
</div>
<div class="showcase-wrapper">
    <div class="container">
        <div class="page-header">
            <h2><a name="showcase"></a>Showcase <small>Cakes / Cupcakes</small></h2>
        </div>
        <div class="row">
            <div class="col-md-6">
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/mario-luigi-thumb.jpg" data-fullimage="/img/photos/mario-luigi.jpg" alt="Mario and Luigi Birthday Cake" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Mario and Luigi</h4>
                        <p class="hidden-xs">This was a Mario Brothers 4UP birthday cake for two twin boys.</p>
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/buzz-lightyear-thumb.jpg" data-fullimage="/img/photos/buzz-lightyear.jpg" alt="Buzz Lightyear Birthday Cake" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Buzz Lightyear</h4>
                        <p class="hidden-xs">A birthday cake for a Toy Story lover. Buzz Lightyear and his alien friend.</p>
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/princess-thumb.jpg" data-fullimage="/img/photos/princess-cake.jpg" alt="Beautiful Princess Cake" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Beautiful Princess</h4>
                        <p class="hidden-xs">Every princess wants a princess cake!</p>
                    </div>
                </div>
            </div>
            <div class="col-md-6">
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/apple-thumb.jpg" data-fullimage="/img/photos/apple-spice-cupcakes.jpg" alt="Apple Spice Cupcakes" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Apple Spice Cupcakes</h4>
                        <p class="hidden-xs">Beautiful and delicious apple spice cupcakes with jelly filling and butter cream frosting!</p>
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/sesame-street-thumb.jpg" data-fullimage="/img/photos/sesame-street-cupcakes.jpg" alt="Sesame Street Cupcakes" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Sesame Street Cupcakes</h4>
                        <p class="hidden-xs">That irresistible fluffy icing makes me love Sesame Street all over again.</p>
                    </div>
                </div>
                <div class="media">
                    <a class="pull-left thumbnail-popup-trigger" href="#">
                        <img class="media-object frame img-responsive" src="/img/photos/pumpkin-patch-thumb.jpg" data-fullimage="/img/photos/pumpkin-patch-cupcakes.jpg" alt="Pumpkin Patch Cupcakes" />
                    </a>
                    <div class="media-body">
                        <h4 class="media-heading">Pumpkin Patch Cupcakes</h4>
                        <p class="hidden-xs">Cupcakes are "in" any day of the year. Welcome the Fall with these tasty pumpkin patch cupcakes :)</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="thumbnail-popup" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    <h4 class="modal-title"></h4>
                </div>
                <div class="modal-body">

                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="customcakes-wrapper">
    <div class="container">
        <h2><a name="custom-cakes"></a>Do You Need a <em>CUSTOM CAKE</em>?</h2>
        <div class="row">
            <div class="col-xs-8 col-md-8">
                <div class="word-cloud hidden-xs hidden-sm" style="position:relative;">
                    <span style="font-family:'Monotype Corsiva'; font-size:48px;">Anniversary Cake</span>
                    <span style="font-family:'Mystery Quest', cursive; font-size:42px; position:absolute; top:50px; left:500px;">Birthday Cake</span>
                    <span style="font-family:'Bigelow Rules', cursive; font-size:48px; position:absolute; top:110px; left:220px;">Baby Gender Reveal Cake</span>
                    <span style="font-family:'Cherry Swash', cursive; font-size:48px; font-weight: bold; position:absolute; top:200px; left:20px;">Seasonal Cakes</span>
                    <span style="font-family:'Shadows Into Light Two', cursive; font-size:33px; position:absolute; top:280px; left:400px;">Announcement Cakes</span>
                    <span style="font-family:'The Girl Next Door', cursive; font-size:92px; position:absolute; top:400px; left:0px; text-decoration: underline;">OR JUST BECAUSE</span>
                </div>
                <div class="hidden-md hidden-lg">
                    <p>Every celebration deserves cake!</p>
                    <p>Consider ordering a custom cake for any event, big or small.</p>
                    <p>We do birthdays, baby showers, baby announcements, anniversary cakes for two, seasonal cakes and more!</p>
                    <p>Contact us today.</p>
                </div>
            </div>
            <div class="col-xs-4 col-md-4">
                <img src="/img/photos/becka-cake.jpg" class="frame img-responsive" />
            </div>
        </div>
        
    </div>
    <div class="bottom"></div>
</div>
<div class="about-wrapper">
    <div class="container">
        <h2><a name="about"></a>About Us</h2>
        <p>Sweet Cakes of Virginia Beach is a owned and operated by <em>BECKA YAWMAN</em>.</p>
        <br />
        <p>Our passion is crafting <em>BEAUTIFUL</em> and <em>DELICIOUS</em> cakes for any occasion.</p>
        <br />
        <p>Contact us today if you want a custom cake for your next event!</p>
    </div>
</div>
<div class="contact-wrapper">
    <div class="container">
        <h2><a name="contact"></a>Contact Us</h2>
        <?php if (isset($this->successMessages)): ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <?php foreach ($this->successMessages as $message): ?>
                    <p><?php echo $escaper->escapeHtml($message); ?></p>
                <?php endforeach; ?>
            </div>
        <?php endif; ?>
        <?php if (isset($this->mailException)): ?>
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>Oh no! An error occured while emailing your form. Please try again :(</p>
                <!-- <?php echo $this->mailException(); ?> -->
            </div>
        <?php endif; ?>
        <?php $validationMessages = $this->form->getMessages(); ?>
        <?php if (!empty($validationMessages)): ?>
            <div class="alert alert-danger alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
                <p>Oops! There was a problem with the data entered into the form :(</p>
                <!-- <?php print_r($validationMessages); ?> -->
            </div>
        <?php endif; ?>
        <?php $this->form->prepare(); ?>
        <form action="<?php echo $this->url('home'); ?>#contact" method="post">
            <div class="row">
                <div class="col-lg-4">
                    <div class="form-group <?php echo (isset($validationMessages['name']) ? 'has-error' : ''); ?> ">
                        <?php echo $this->formRow($this->form->get('name')) ?>
                    </div>
                    <div class="form-group <?php echo (isset($validationMessages['email']) ? 'has-error' : ''); ?>">
                        <?php echo $this->formRow($this->form->get('email')) ?>
                    </div>
                    <div class="form-group <?php echo (isset($validationMessages['comments']) ? 'has-error' : ''); ?>">
                        <?php echo $this->formRow($this->form->get('comments')) ?>
                    </div>
                    <?php echo $this->formElement($this->form->get('security')) ?>
                    <?php echo $this->formElement($this->form->get('submit')) ?>
                </div>
                <div class="col-lg-8 facebook">
                    <div id="fb-root"></div>
                    <script>(function(d, s, id) {
                        var js, fjs = d.getElementsByTagName(s)[0];
                        if (d.getElementById(id)) return;
                        js = d.createElement(s); js.id = id;
                        js.src = "//connect.facebook.net/en_US/all.js#xfbml=1";
                        fjs.parentNode.insertBefore(js, fjs);
                    }(document, 'script', 'facebook-jssdk'));</script>
                    <div class="fb-like-box" data-href="https://www.facebook.com/vbSweetCake" data-width="600px" data-height="The pixel height of the plugin" data-colorscheme="light" data-show-faces="false" data-header="true" data-stream="true" data-show-border="true"></div>
                </div>
            </div>
        </form>
    </div>
    <div class="bottom"></div>
</div>